import { StyleOption, GalleryItem, Language } from './types';

export const STYLES: StyleOption[] = [
  {
    id: 1,
    prompt: "Modern vector art portrait, thick clean outlines, smooth cel-shaded gradients, vibrant colors, clear facial features",
    previewColor: "bg-blue-500"
  },
  {
    id: 2,
    prompt: "Analog marker style portrait, expressive ink lines, visible marker stroke textures, organic sketchbook feel",
    previewColor: "bg-orange-500"
  },
  {
    id: 3,
    prompt: "Ligne Claire style portrait, vector lines, uniform thickness, flat solid colors, no gradients, high-contrast minimalist face",
    previewColor: "bg-yellow-400"
  },
  {
    id: 4,
    prompt: "Risograph print style portrait, visible halftone dots, limited color palette (e.g., pink, blue, yellow), slight color misalignment",
    previewColor: "bg-pink-500"
  },
  {
    id: 5,
    prompt: "Bold 2.5D stylized portrait, fluid outlines, rim lighting, smooth matte texture, charismatic semi-realistic expression",
    previewColor: "bg-red-500"
  },
  {
    id: 6,
    prompt: "Traditional watercolor portrait, loose ink pen outlines, soft water color bleeds and stains, artistic and elegant",
    previewColor: "bg-teal-400"
  },
  {
    id: 7,
    prompt: "Tech-industrial vinyl toy bust, matte plastic finish, framed in a spec sheet layout with UI elements, stylized character",
    previewColor: "bg-slate-600"
  },
  {
    id: 8,
    prompt: "Graphic novel ink portrait, thick clean outlines, heavy comic book shadows, sharp angular lines, high-contrast, dramatic lighting",
    previewColor: "bg-indigo-600"
  },
  {
    id: 9,
    prompt: "Colored pencil sketch portrait, expressive hand-drawn lines, visible soft pencil strokes, layered and blended colors, textured paper feel",
    previewColor: "bg-amber-600"
  },
  {
    id: 10,
    prompt: "1930s vintage animation style, monochrome palette, simple rounded shapes, bouncy and fluid black lines, expressive eyes",
    previewColor: "bg-gray-800"
  },
  {
    id: 11,
    prompt: "Film Noir movie still portrait, high-contrast black and white, dramatic chiaroscuro lighting, heavy shadows, mysterious mood",
    previewColor: "bg-neutral-900"
  },
  {
    id: 12,
    prompt: "Impressionist oil painting portrait, visible and thick impasto brushstrokes, rich color blending, focus on light and shadow",
    previewColor: "bg-violet-600"
  }
];

export const TRANSLATIONS = {
  'zh-TW': {
    header_title: "Sticker Maker Pro",
    header_subtitle: "AI 貼圖製作工具",
    nav_create: "製作貼圖",
    nav_gallery: "探索藝廊",
    nav_history: "我的貼圖集",
    welcome_title: "歡迎使用 Sticker Maker Pro!",
    welcome_desc: "請上傳一張肖像照片開始製作！如果您沒有指定風格，我會預設使用",
    welcome_default_style: "[1] 向量賽璐珞風格",
    step1_title: "1. 選擇風格",
    step1_selected: "目前選擇",
    step2_title: "2. 上傳肖像照片",
    step2_drag: "點擊或拖放照片至此",
    step2_hint: "支援 JPG, PNG (建議使用清晰的半身肖像)",
    step2_ready: "照片準備就緒！",
    step2_reedit: "重新編輯",
    step2_change: "更換照片",
    editor_title: "調整您的照片",
    editor_desc: "請縮放、移動或旋轉，確保主體位於中央以獲得最佳效果。",
    editor_btn_confirm: "確認使用",
    editor_btn_cancel: "取消",
    editor_rotate: "旋轉",
    editor_zoom: "縮放",
    processing_title: "製作中",
    processing_steps: [
      "正在初始化 Sticker Maker Pro...",
      "步驟 2/4: 智慧去背與主體分離中...",
      "步驟 3/4: 應用風格與向量化轉換...",
      "步驟 4/4: 最終驗證與裁切...",
    ],
    result_verified: "驗證通過：512x512px PNG",
    result_title: "您的貼圖已完成！",
    result_style_label: "風格",
    result_saved: "已儲存至您的貼圖集",
    btn_magic_wand: "一鍵去背修復",
    btn_reset: "製作下一張",
    btn_reuse: "用同張圖換風格",
    btn_download: "下載 PNG",
    error_upload: "讀取檔案時發生錯誤",
    error_process: "製作失敗，請稍後再試或更換照片。",
    footer: "© 2024 Sticker Maker Pro. Powered by Google Gemini.",
    gallery_title: "社群作品藝廊",
    gallery_subtitle: "探索來自全球的創意貼圖",
    gallery_btn_try: "試試這個風格",
    history_title: "我的貼圖集",
    history_subtitle: "您在本機製作的所有貼圖",
    history_empty: "尚未製作任何貼圖。快去製作第一張吧！",
    styles: {
      1: { name: "向量賽璐珞風", features: "粗黑輪廓、平滑漸層" },
      2: { name: "手繪麥克筆風", features: "手繪線條、筆觸感" },
      3: { name: "極簡平塗風", features: "純色塊、無漸層" },
      4: { name: "孔版印刷風", features: "網點、錯位疊印" },
      5: { name: "美式卡通風", features: "粗線條、微立體感" },
      6: { name: "水彩暈染風", features: "墨水線、水漬感" },
      7: { name: "科技工業風", features: "啞光、未來感、框線" },
      8: { name: "圖像小說風", features: "漫畫風格、高對比陰影" },
      9: { name: "色鉛筆素描風", features: "柔軟筆觸、疊色層次" },
      10: { name: "復古橡膠管卡通", features: "30年代動畫、黑白線條" },
      11: { name: "黑白電影偵探風", features: "純黑白、強烈光影" },
      12: { name: "印象派油畫風", features: "可見筆觸、厚塗顏料" },
    }
  },
  'en': {
    header_title: "Sticker Maker Pro",
    header_subtitle: "AI Sticker Generator",
    nav_create: "Create",
    nav_gallery: "Gallery",
    nav_history: "Collection",
    welcome_title: "Welcome to Sticker Maker Pro!",
    welcome_desc: "Upload a portrait photo to start! If no style is specified, I will default to",
    welcome_default_style: "[1] Modern Vector Style",
    step1_title: "1. Choose Style",
    step1_selected: "Selected",
    step2_title: "2. Upload Photo",
    step2_drag: "Click or drag photo here",
    step2_hint: "Supports JPG, PNG (Clear portrait recommended)",
    step2_ready: "Photo Ready!",
    step2_reedit: "Edit",
    step2_change: "Change Photo",
    editor_title: "Adjust Your Photo",
    editor_desc: "Zoom, pan, and rotate to frame the subject perfectly.",
    editor_btn_confirm: "Confirm",
    editor_btn_cancel: "Cancel",
    editor_rotate: "Rotate",
    editor_zoom: "Zoom",
    processing_title: "Processing",
    processing_steps: [
      "Initializing Sticker Maker Pro...",
      "Step 2/4: Removing background...",
      "Step 3/4: Applying style & vectorizing...",
      "Step 4/4: Final validation & cropping...",
    ],
    result_verified: "Verified: 512x512px PNG",
    result_title: "Sticker Ready!",
    result_style_label: "Style",
    result_saved: "Saved to Collection",
    btn_magic_wand: "Fix Background",
    btn_reset: "Start New",
    btn_reuse: "Reuse Photo",
    btn_download: "Download PNG",
    error_upload: "Error reading file",
    error_process: "Processing failed, please try again or use a different photo.",
    footer: "© 2024 Sticker Maker Pro. Powered by Google Gemini.",
    gallery_title: "Community Gallery",
    gallery_subtitle: "Explore creative stickers from around the world",
    gallery_btn_try: "Try this style",
    history_title: "My Collection",
    history_subtitle: "All stickers you created on this device",
    history_empty: "No stickers yet. Go create your first one!",
    styles: {
      1: { name: "Modern Vector", features: "Thick outlines, smooth gradients" },
      2: { name: "Analog Marker", features: "Expressive ink lines, marker texture" },
      3: { name: "Ligne Claire", features: "Flat colors, no gradients, minimalist" },
      4: { name: "Risograph", features: "Halftone dots, color misalignment" },
      5: { name: "American Cartoon", features: "Bold 2.5D, fluid outlines" },
      6: { name: "Watercolor", features: "Soft bleeds, ink outlines" },
      7: { name: "Tech Industrial", features: "Matte plastic, UI elements" },
      8: { name: "Graphic Novel", features: "Heavy shadows, high contrast" },
      9: { name: "Colored Pencil", features: "Soft strokes, layered colors" },
      10: { name: "Rubber Hose", features: "1930s animation, monochrome" },
      11: { name: "Film Noir", features: "Black & white, dramatic lighting" },
      12: { name: "Impressionist", features: "Thick brushstrokes, light & shadow" },
    }
  },
  'ja': {
    header_title: "Sticker Maker Pro",
    header_subtitle: "AIステッカー作成ツール",
    nav_create: "作成",
    nav_gallery: "ギャラリー",
    nav_history: "コレクション",
    welcome_title: "Sticker Maker Proへようこそ!",
    welcome_desc: "写真をアップロードして始めましょう！スタイルが指定されていない場合、デフォルトで",
    welcome_default_style: "[1] ベクターセルロイド風",
    step1_title: "1. スタイルを選択",
    step1_selected: "選択中",
    step2_title: "2. 写真をアップロード",
    step2_drag: "クリックまたは写真をドラッグ",
    step2_hint: "JPG, PNG対応 (鮮明なポートレート推奨)",
    step2_ready: "写真の準備完了！",
    step2_reedit: "編集する",
    step2_change: "写真を変更",
    editor_title: "写真を調整",
    editor_desc: "拡大・縮小、移動、回転を行い、被写体を中央に配置してください。",
    editor_btn_confirm: "完了",
    editor_btn_cancel: "キャンセル",
    editor_rotate: "回転",
    editor_zoom: "ズーム",
    processing_title: "作成中",
    processing_steps: [
      "初期化中...",
      "ステップ 2/4: 背景除去中...",
      "ステップ 3/4: スタイル適用中...",
      "ステップ 4/4: 最終確認中...",
    ],
    result_verified: "検証済み：512x512px PNG",
    result_title: "ステッカー完成！",
    result_style_label: "スタイル",
    result_saved: "コレクションに保存しました",
    btn_magic_wand: "背景を修正",
    btn_reset: "新規作成",
    btn_reuse: "同じ写真で作成",
    btn_download: "PNGをダウンロード",
    error_upload: "ファイルの読み込みエラー",
    error_process: "作成に失敗しました。もう一度試すか、別の写真を使用してください。",
    footer: "© 2024 Sticker Maker Pro. Powered by Google Gemini.",
    gallery_title: "コミュニティギャラリー",
    gallery_subtitle: "世界中のクリエイティブなステッカーを探そう",
    gallery_btn_try: "このスタイルで作成",
    history_title: "マイコレクション",
    history_subtitle: "このデバイスで作成したすべてのステッカー",
    history_empty: "まだステッカーがありません。最初の1枚を作成しましょう！",
    styles: {
      1: { name: "ベクターセルロイド風", features: "太い輪郭、滑らかなグラデーション" },
      2: { name: "手描きマーカー風", features: "インクの線、マーカーの質感" },
      3: { name: "ミニマルベタ塗り風", features: "単色、グラデーションなし" },
      4: { name: "リソグラフ印刷風", features: "網点、版ズレ効果" },
      5: { name: "アメリカンカートゥーン", features: "太い線、2.5D的な立体感" },
      6: { name: "水彩画風", features: "インクの輪郭、水彩の滲み" },
      7: { name: "テック工業風", features: "マットな質感、UI要素" },
      8: { name: "グラフィックノベル風", features: "コミック調、強いコントラスト" },
      9: { name: "色鉛筆スケッチ風", features: "柔らかい筆致、重ね塗り" },
      10: { name: "レトロラバーホース", features: "1930年代アニメ、モノクロ" },
      11: { name: "フィルム・ノワール風", features: "白黒、ドラマチックな照明" },
      12: { name: "印象派油絵風", features: "厚塗り、光と影の表現" },
    }
  }
};

export const GALLERY_ITEMS: GalleryItem[] = [
  { id: '1', imageUrl: 'https://placehold.co/512x512/4F46E5/FFFFFF.png?text=Vector+Boy', styleId: 1, author: 'User123' },
  { id: '2', imageUrl: 'https://placehold.co/512x512/EA580C/FFFFFF.png?text=Marker+Girl', styleId: 2, author: 'ArtFan' },
  { id: '3', imageUrl: 'https://placehold.co/512x512/FACC15/000000.png?text=Minimal+Cat', styleId: 3, author: 'Minimalist' },
  { id: '4', imageUrl: 'https://placehold.co/512x512/EC4899/FFFFFF.png?text=Riso+Print', styleId: 4, author: 'PrintMaster' },
  { id: '5', imageUrl: 'https://placehold.co/512x512/EF4444/FFFFFF.png?text=Cartoon+Hero', styleId: 5, author: 'ToonLover' },
  { id: '6', imageUrl: 'https://placehold.co/512x512/2DD4BF/FFFFFF.png?text=Watercolor', styleId: 6, author: 'WaterColorist' },
  { id: '7', imageUrl: 'https://placehold.co/512x512/475569/FFFFFF.png?text=Cyber+Punk', styleId: 7, author: 'Techie' },
  { id: '8', imageUrl: 'https://placehold.co/512x512/4F46E5/FFFFFF.png?text=Noir+Scene', styleId: 8, author: 'Detective' },
];
